In [3]:
# createing the nd arrays
# we are using the numpy to do all the things

In [4]:
import numpy as np

In [5]:
arr1=np.array([1,2,2,3,5])# this fn directly change the list in the n-d array based on the list dimensions
arr1

array([1, 2, 2, 3, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr2=np.arange(24).reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
arr2[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [9]:
np.vsplit(arr2,6)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [10]:
np.hsplit(arr2,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

In [11]:
arr3=np.arange(25).reshape(5,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
arr3[arr3>20]

array([21, 22, 23, 24])

In [13]:
arr3[(arr3>10)&(arr3%2!=0)]

array([11, 13, 15, 17, 19, 21, 23])

In [16]:
arr3[(arr3>10)&(arr3%2!=0)]=0
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10,  0, 12,  0, 14],
       [ 0, 16,  0, 18,  0],
       [20,  0, 22,  0, 24]])

In [20]:
arr4 =np.arange(20,30).reshape(5,2)
arr4.sort()

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])